# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitmirror" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "3dcbcefc4ecd96bf375af606a793748b874e2d8eca57a7b932d1d5044cb8f772"
      url "https://github.com/wimwenigerkind/gitmirror/releases/download/v#{version}/gitmirror_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d161e96f6ec094c2009d265861cdd3e2b9f7fdb04fd711e8bdef697d4315f267"
      url "https://github.com/wimwenigerkind/gitmirror/releases/download/v#{version}/gitmirror_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "327321ca69a13e22ad47b3059bc0e6ce0ef1684e0bd0b85df0f4a2295492eaa6"
      url "https://github.com/wimwenigerkind/gitmirror/releases/download/v#{version}/gitmirror_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d8a824bac0c6e151466fdaafb968c6287dfc6969c9873f9b07e6c110f0709cd8"
      url "https://github.com/wimwenigerkind/gitmirror/releases/download/v#{version}/gitmirror_Linux_arm64.tar.gz"
    end
  end

  name "gitmirror"
  desc "Mirror repositories from git hosting providers to local bare clones"
  homepage "https://github.com/wimwenigerkind/gitmirror"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitmirror"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitmirror"]
    end
  end

  # No zap stanza required

end
