# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitmirror" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "db060c6833854aadb4e657190e99414df9f50f649a220f93b5b8b144714cc5ab"
      url "https://github.com/wimwenigerkind/gitmirror/releases/download/v#{version}/gitmirror_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1374ada00d9c10ee33f81a38e5e324d170978253d3e0d18b7f391e7a775883e6"
      url "https://github.com/wimwenigerkind/gitmirror/releases/download/v#{version}/gitmirror_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b925b9e889635f1c804a4d0f004bab8a7887554f223bb10e41b66398d9139550"
      url "https://github.com/wimwenigerkind/gitmirror/releases/download/v#{version}/gitmirror_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4526fd54c4540121f5d9fdc1d197ca9ab14718f58cb44f733535ed8dd125b774"
      url "https://github.com/wimwenigerkind/gitmirror/releases/download/v#{version}/gitmirror_Linux_arm64.tar.gz"
    end
  end

  name "gitmirror"
  desc "Mirror repositories from git hosting providers to local bare clones"
  homepage "https://github.com/wimwenigerkind/gitmirror"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitmirror"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitmirror"]
    end
  end

  # No zap stanza required

end
