# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitmirror" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "d29aeade36db7bfc1a53c2604f31f936a19bb7e63bf6c0d9e8933840e8e5255d"
      url "https://github.com/wimwenigerkind/gitmirror/releases/download/v#{version}/gitmirror_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e8f508935b3848333f5ff814280139be3a1e4d269774c318dcc4da4884fe2e02"
      url "https://github.com/wimwenigerkind/gitmirror/releases/download/v#{version}/gitmirror_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "42905ac1abba426dd35d56b6deb5beb9e9500105597fac1684f35b18a00b0f26"
      url "https://github.com/wimwenigerkind/gitmirror/releases/download/v#{version}/gitmirror_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8a5b2c3f25e5627bb2e4a79f3eebdce56d2b91ba5b09b40e5ef04daf3d55404d"
      url "https://github.com/wimwenigerkind/gitmirror/releases/download/v#{version}/gitmirror_Linux_arm64.tar.gz"
    end
  end

  name "gitmirror"
  desc "Mirror repositories from git hosting providers to local bare clones"
  homepage "https://github.com/wimwenigerkind/gitmirror"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitmirror"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitmirror"]
    end
  end

  # No zap stanza required

end
