# This file was generated by GoReleaser. DO NOT EDIT.
cask "odoopack" do
  version "0.0.8"

  on_macos do
    on_intel do
      sha256 "63a559831b83abe1d0beee19968a2980df26b6b1918e6e3180417ebb69b3d488"
      url "https://github.com/wimwenigerkind/odoopack/releases/download/v#{version}/odoopack_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "aa4bea337054f4dc2d987a3a14aa66bea147e30de105754fec33cb9af6b6c9e7"
      url "https://github.com/wimwenigerkind/odoopack/releases/download/v#{version}/odoopack_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d229a5d2b6354df259542c78000c767b3d67711ab433cf14939aa7e470aee645"
      url "https://github.com/wimwenigerkind/odoopack/releases/download/v#{version}/odoopack_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6a84afdfdd2c2bf8d2a5e4bdb567c0b7763748dc8fd041aa33b14ca9464b48e9"
      url "https://github.com/wimwenigerkind/odoopack/releases/download/v#{version}/odoopack_Linux_arm64.tar.gz"
    end
  end

  name "odoopack"
  desc "Package manager for Odoo 19 addons"
  homepage "https://github.com/wimwenigerkind/odoopack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "odoopack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/odoopack"]
    end
  end

  # No zap stanza required

end
