# This file was generated by GoReleaser. DO NOT EDIT.
cask "odoopack" do
  version "0.0.7"

  on_macos do
    on_intel do
      sha256 "b9893e516ca1ab04a50eb5463020f6604fcba79385665e38442a78afeec9393d"
      url "https://github.com/wimwenigerkind/odoopack/releases/download/v#{version}/odoopack_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3bc1f53701564527e8b6689211306e554ca7d50b9d79123dca6499a2160c99aa"
      url "https://github.com/wimwenigerkind/odoopack/releases/download/v#{version}/odoopack_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "91e98062bd4400b780a63a9686a474934269319276a475b3ca2199fc963eaa92"
      url "https://github.com/wimwenigerkind/odoopack/releases/download/v#{version}/odoopack_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "27f2cb898f466420f31fcc41aeb83219afc4e49fb7e127254ebcc4a8ca10aaee"
      url "https://github.com/wimwenigerkind/odoopack/releases/download/v#{version}/odoopack_Linux_arm64.tar.gz"
    end
  end

  name "odoopack"
  desc "Package manager for Odoo 19 addons"
  homepage "https://github.com/wimwenigerkind/odoopack"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "odoopack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/odoopack"]
    end
  end

  # No zap stanza required

end
