# This file was generated by GoReleaser. DO NOT EDIT.
cask "odoopack" do
  name "odoopack"
  desc "Package manager for Odoo 19 addons"
  homepage "https://github.com/wimwenigerkind/odoopack"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "odoopack"

  on_macos do
    on_intel do
      url "https://github.com/wimwenigerkind/odoopack/releases/download/v#{version}/odoopack_Darwin_x86_64.tar.gz"
      sha256 "0e2beb2070070873df0b253f3d63f70a048dbb8782e228dcf3f9a8ff433ed882"
    end
    on_arm do
      url "https://github.com/wimwenigerkind/odoopack/releases/download/v#{version}/odoopack_Darwin_arm64.tar.gz"
      sha256 "e2130e58ae06bf98da267f5c8cdf27392ccbe2e94fb02fa696df09425220141c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wimwenigerkind/odoopack/releases/download/v#{version}/odoopack_Linux_x86_64.tar.gz"
      sha256 "343412f6b0e72b5d006860c678042c0e5b314ff2d0ea408b4de6e04c8b5d1d57"
    end
    on_arm do
      url "https://github.com/wimwenigerkind/odoopack/releases/download/v#{version}/odoopack_Linux_arm64.tar.gz"
      sha256 "324951f737b93e6ddf42c2bb12ac712b28ad42751d816e3a6445635ea3b208e4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/odoopack"]
    end
  end

  # No zap stanza required
end
