# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wswcli < Formula
  desc "wswcli"
  homepage "https://github.com/wimwenigerkind/wswcli"
  version "2.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wimwenigerkind/wswcli/releases/download/v2.4.1/wswcli_Darwin_x86_64.tar.gz"
      sha256 "cba2bf906ca4ff03bdd8b62bab276ad209d11a1db0ee5233a216ad15cc30e7c4"

      def install
        bin.install "wswcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wimwenigerkind/wswcli/releases/download/v2.4.1/wswcli_Darwin_arm64.tar.gz"
      sha256 "7470315f8a45f817798fa5144c6d317efd0adb8645fb73a8dddb11e5c22b45f2"

      def install
        bin.install "wswcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/wimwenigerkind/wswcli/releases/download/v2.4.1/wswcli_Linux_x86_64.tar.gz"
      sha256 "9fdee8e931a2e3f2ddfae58eb8c30cf008fc2c3aa0c7ed1264dc8554950bb06d"
      def install
        bin.install "wswcli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/wimwenigerkind/wswcli/releases/download/v2.4.1/wswcli_Linux_arm64.tar.gz"
      sha256 "7c9cd60b3b5030586e2d579ea98d2de2bc7272121dd2bda5cd8b22ebd7b4233f"
      def install
        bin.install "wswcli"
      end
    end
  end

  test do
    system "#{bin}/wswcli", "--version"
  end
end
