# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wswcli < Formula
  desc "wswcli"
  homepage "https://github.com/wimwenigerkind/wswcli"
  version "2.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wimwenigerkind/wswcli/releases/download/v2.4.0/wswcli_Darwin_x86_64.tar.gz"
      sha256 "1ce39ca1bb44280de0bc31a5b1bb8deb7c780daf03ae6cbd91582c4e3e963f6d"

      def install
        bin.install "wswcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wimwenigerkind/wswcli/releases/download/v2.4.0/wswcli_Darwin_arm64.tar.gz"
      sha256 "82b62d747ca529c722465a345cf877a931a9c82a701fa8eb0621d62dfcd33001"

      def install
        bin.install "wswcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/wimwenigerkind/wswcli/releases/download/v2.4.0/wswcli_Linux_x86_64.tar.gz"
      sha256 "7027ce71f3557e8e16f483d6508560e80f296773c7c65e21284c31367f11d4c7"
      def install
        bin.install "wswcli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/wimwenigerkind/wswcli/releases/download/v2.4.0/wswcli_Linux_arm64.tar.gz"
      sha256 "75173fa7434c769700771b67581df97c99a84ecb8387e8a8b3cea0d396d86c89"
      def install
        bin.install "wswcli"
      end
    end
  end

  test do
    system "#{bin}/wswcli", "--version"
  end
end
